### PR TITLE
Use UTR #51 Unicode Emoji, Version 2.0.0 data

### PR DESCRIPTION
**Pull request by mathiasbynens**
**_WIP! Do not merge yet.**_

Ref. #1.

### CODE REVIEW

**Comment by mathiasbynens** [comment]
The source data has a new format:

```
# Warning: the format has changed from Version 1.0
# Format: 
# codepoint(s) ; property=Yes # [count] (character(s)) name 
```

It’s still easy enough to parse, but we may have to rethink the way this module exports data. Rather than a single array of code points and an array of symbols we should probably categorize them.

**Comment by beaugunderson** [comment]
It would be nice to include the sequences (keycaps, emoji with skin-tone modifiers) and ZWJ (the family emoji) as well (contained in the other two files in that directory).

**Comment by cameronhunter** [comment]
I took a stab at this [over here](https://github.com/cameronhunter/unicode-tr51-emoji) using a PEG.js grammar as opposed to hand-rolling a parser. It parses v1.0 and v2.0 file formats and exports them in an API compatible format to this repo.

**Comment by cameronhunter** [comment]
I've just released a new version of [unicode-tr51-emoji](https://github.com/cameronhunter/unicode-tr51-emoji) which parses v1.0 - v4.0 of TR#51. It also parses and includes sequences and zwj-sequences.

/cc @beaugunderson

**Pull request closed without merging**
